package victor.training.performance.completableFuture;

public class TestRootCauseException extends RuntimeException {
}
